travis:
  secure:
    BINSTAR_TOKEN: cL5rcm453e5zPOc3L59HUfWTJTrySY41LkOSoaSFIsDNYWRMZyHPt9T1V1FTcF2tZ5P3Z3p0v3Z4DYGyQMCdyV4boPc0B7sQ8ayMSrjiw+hVhu7GHhV3gCJDeqoSrplJBAsJexjome8Th0qkej0gqhnBOOGMTsYe6yNKdFGCWgYZlgnoxdGIbw0lxoSi3G+eiL62SYq9gKW6t56/j3Ta2C+tYpZz7ZkA98sD4agJOzmIfV5Xk5G8/AJRy4BYFY+6SNdgYEH3+XwBKAe55FyAVv6zGCai7yDmcdTok/mW1H2iSu95fVCIMSzjTSjYC/5I1r/eLJ/3WhIaboJ13B6JpUNlG4kKtP02rPQle+UOKSEoahtV4VUp2hYr9bjanJ9EJAhNjKrWotx2g9ycTPXeCbZ4VE9/f0n7OerMusKNkWLYzc6syQLc1KaHInwpPz7U7T2+pDIO+FsklIoyCF/qjgLPr3J4UmXkptYBzWevcBD9KRB6/+mhUsVOwvSijhTFb3FALjV28h/muJ3auu0PHF+3suY4QDh22ob5WGd1qS5eaHY0cKPYLLMAhnQeyIsn0deg+5Jn+/2hZ+Rwh4EHM1CoGSYmOf688QBNr0twEYPdE9JOaHw9/NW5K7qoCHvrIf+gWZvdSsYQSD+2zLQepo67RXb7cawHne895HfzNCQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
